"""add fields in user model

Revision ID: ed0a15432624
Revises: 451e07153416
Create Date: 2025-05-02 18:54:06.430815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0a15432624'
down_revision: Union[str, None] = '451e07153416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'created_at')
    op.drop_column('clients', 'password_hash')
    # ### end Alembic commands ###
